export const bannedWords: string[] = [
    "alboche",
    "allez bien vous faire cuire le cul",
    "amerlo",
    "amerloque",
    "angliche",
    "asiate",
    "asiate(s)",
    "asiates",
    "ass",
    "asshole",
    "b i t e",
    "balai à chiotte",
    "bamboula",
    "bande d’abrutis",
    "bander",
    "biatch",
    "bitch",
    "bite",
    "bitembois",
    "Bitembois",
    "boche",
    "bouffon",
    "bouffonne",
    "bouffonnes",
    "bougnoul",
    "bougnoul",
    "bougnoule",
    "gourgandine",
    "Bougnoulie",
    "bougnoulisation",
    "bougnouliser",
    "bounioul",
    "branler",
    "branlette",
    "branleur",
    "branquignole",
    "brise burne",
    "brise burnes",
    "brise-burnes",
    "c u l",
    "c0nnasse",
    "C0nnasse",
    "c0nnasses",
    "C0nnasses",
    "casse-gonades",
    "chicano",
    "chicanos",
    "chien de chrétien",
    "chier",
    "Chinetoque",
    "chinetoque",
    "chleuh",
    "con",
    "connasse",
    "Connasse",
    "connasses",
    "Connasses",
    "connerie",
    "couille molle",
    "Couille molle",
    "crouille",
    "crouilles",
    "cul",
    "débile",
    "Débile",
    "débiles",
    "Débiles",
    "débougnouliser",
    "dégouiner",
    "dick",
    "doryphore",
    "ducon",
    "duconnot",
    "dukon",
    "emmerder",
    "emmerdeuse",
    "emmerdeuses",
    "empapaouté",
    "enculé",
    "enculé de ta race",
    "enfant de fusil",
    "enfant de garce",
    "enfant de putain",
    "enfant de pute",
    "enfant de salaud",
    "enfoiré",
    "envaselineur",
    "espingoin",
    "f u",
    "f u ck",
    "face de citron",
    "facka",
    "faire cuire le cul",
    "FDP",
    "F D P",
    "fdp",
    "femmelette",
    "ferme ta g",
    "Ferme ta gueule",
    "ferme tg",
    "fermer sa gueule",
    "filloniste",
    "fils de bâtard",
    "fils de chien",
    "fils de pute",
    "fils de pute",
    "fils de yack",
    "Fini à la pisse",
    "fridolin",
    "ftg",
    "fuck",
    "fucker",
    "fucking",
    "fuckoff",
    "fum",
    "fuq",
    "fuqa",
    "gang bang",
    "garage à bite",
    "gogol",
    "gogole",
    "gogoles",
    "gogolito",
    "goudou",
    "goudous",
    "gouine",
    "goulamas",
    "goulou-goulou",
    "gourdasse",
    "gourdasses",
    "gourgandine",
    "gourgandines",
    "grognards",
    "grognasse",
    "grognasses",
    "gueniches",
    "gueniches",
    "guenillard",
    "guenillards",
    "homéopathe",
    "incel",
    "islamo gauchisme",
    "islamo gauchisme",
    "islamo gauchisme",
    "islamo gauchisme",
    "islamo gauchisme",
    "islamo gauchiste",
    "islamo gauchiste",
    "islamo gauchiste",
    "islamo-gauchisme",
    "islamo-gauchiste",
    "islamogauchisme",
    "islamogauchisme",
    "islamogauchiste",
    "islamogauchiste",
    "jean foutre",
    "jean-foutre",
    "jeanfoutre",
    "judéo-bellicisme",
    "judéo-belliciste",
    "K0nnasse",
    "K0nnasse",
    "K0nnasses",
    "K0nnasses",
    "Konnasse",
    "Konnasse",
    "Konnasses",
    "Konnasses",
    "lepéniste",
    "Lopette",
    "macroniste",
    "maddafacka",
    "maddafacka (<3)",
    "mbdtc",
    "mélenchoniste",
    "merde",
    "merdes",
    "merdeuse",
    "merdeuses",
    "merdouillard",
    "minus",
    "n t m",
    "n t m",
    "N T M",
    "nabot",
    "nègre",
    "negro",
    "negre",
    "négresse",
    "négresses",
    "négrillon",
    "négrillons",
    "négro",
    "niakoué",
    "nique",
    "nique ta mère",
    "nique ta mère",
    "ntm",
    "ntm",
    "NTM",
    "p d",
    "p é d é",
    "p u t a i n",
    "p0rn",
    "peau de couille",
    "pédé",
    "peigne-cul",
    "peigne-zizi",
    "pelle à brin",
    "pelle à merde",
    "péquenaud",
    "petite bite",
    "pimfle",
    "pleutre",
    "polack",
    "polaque",
    "porcasse",
    "porn",
    "porno",
    "pot de merde",
    "pot de merde",
    "pouf",
    "pouffe",
    "pouffiasse",
    "pouffre",
    "pouffyase",
    "poufiasse",
    "poufyase",
    "pr0n",
    "pub",
    "putain",
    "pute",
    "pute borgne",
    "puteborgne",
    "raclure de bidet",
    "raclure debidet",
    "raclurede bidet",
    "racluredebidet",
    "ricain",
    "Romano",
    "romano",
    "romanos",
    "Romanos",
    "ruskoff",
    "s a l a u d",
    "sac à merde",
    "sale merde",
    "saleaud",
    "salod",
    "salot",
    "sarkozyste",
    "Schleu",
    "sex",
    "Sidaïque",
    "sidaïque",
    "Sidaïques",
    "sidaïques",
    "sily",
    "simp",
    "Tafiole",
    "tafiole",
    "Tafioles",
    "tafioles",
    "takezen",
    "tant0use",
    "tantouse",
    "tantouses",
    "tantouze",
    "Tantouze",
    "tantouzes",
    "Tantouzes",
    "tarlouse",
    "tarlouze",
    "tarlouzes",
    "termaji",
    "tête de bite",
    "Tocard",
    "torr penn",
    "travelo",
    "travelo",
    "travelos",
    "trou du cul",
    "trou duc",
    "va niquer ta mère",
    "Va te faire composter",
    "virgin",
    "youd",
    "youpin",
    "youtre"]